wazo-platform/wazo-calld

wazo_calld/plugins/voicemails/services.py
In Asterisk `16.3.0-1~wazo6` the endpoint to manage voicemails was changed from `xivo` to `wazo`
There is a test in the Asterisk repo for the REST API to there are no test in Wazo for this feature.
=> voicemail: change the ari endpoint from xivo to wazo

CHANGELOG.md, integration_tests/assets/etc/asterisk/ari.conf, integration_tests/suite/helpers/auth.py, integration_tests/suite/helpers/calld.py, integration_tests/suite/helpers/confd.py, integration_tests/suite/helpers/constants.py, integration_tests/suite/test_switchboards.py, wazo_calld/helpers/confd.py, wazo_calld/plugins/api/api.yml, wazo_calld/plugins/switchboards/api.yml, wazo_calld/plugins/switchboards/confd.py, wazo_calld/plugins/switchboards/exceptions.py, wazo_calld/plugins/switchboards/notifier.py, wazo_calld/plugins/switchboards/plugin.py, wazo_calld/plugins/switchboards/resources.py, wazo_calld/plugins/switchboards/services.py, wazo_calld/plugins/switchboards/stasis.py
switchboard: switch tenant_uuid/switchboard_uuid position
switchboard: use token helper to fetch user_uuid
changelog: standardize style
switchboard: add Wazo-Tenant header to documentation
switchboard: add tenant_uuid header to bus messages
switchboard: make queued_call_answered multi-tenant
switchboard: make held answer multi tenant
switchboard: make hold call multi tenant
switchboard: make answer multi tenant
switchboards: make queued_calls multi-tenant
switchboard: fix register/deregister multi-tenant
switchboard: fix styling issues
=> Pull request for WAZO-691-event-switchboard-tenant

CHANGELOG.md, integration_tests/suite/test_calls.py, integration_tests/suite/test_calls_bus_consume.py, wazo_calld/helpers/ari_.py, wazo_calld/plugins/calls/api.yml, wazo_calld/plugins/calls/events.yml, wazo_calld/plugins/calls/schema.py, wazo_calld/plugins/calls/services.py
calls: add the sip_call_id field
the sip_call_id contains the value of the Call-ID SIP header. it is used to match an event to a call started using a webrtc phone.
without this information the call initiator has to rely on the caller id name and number of the call to "guess" if an event is related to its phone. The guessing method also does not work with multiple calls.
=> Wazo 823 sip call

integration_tests/suite/helpers/ari_.py, integration_tests/suite/helpers/chan_test.py, integration_tests/suite/test_applications.py, wazo_calld/helpers/ari_.py, wazo_calld/helpers/tests/test_ari_helpers.py, wazo_calld/plugins/applications/events.py, wazo_calld/plugins/applications/notifier.py, wazo_calld/plugins/applications/services.py, wazo_calld/plugins/applications/stasis.py, wazo_calld/plugins/applications/tests/test_stasis.py, wazo_calld/plugins/calls/event.py, wazo_calld/plugins/calls/tests/test_event.py
add a `StasisStart` handler for applications with no command which are used for users with lines calling directly into Wazo applications.
=> Wazo 895 user application

wazo_calld/plugins/applications/models.py, wazo_calld/plugins/applications/schema.py
when a call event is published the user_uuid and tenant_uuid fields will be set
if the channel has the appropriate channel variables
=> applications: add the user_uuid and tenant_uuid to the call body

integration_tests/suite/test_applications.py, wazo_calld/ari_.py, wazo_calld/plugins/applications/plugin.py, wazo_calld/plugins/applications/stasis.py
reason: if subscribe() is call more than one time, then ari-py will
trigger callback many time.
=> application: do not subscribe many time on app events

integration_tests/assets/etc/asterisk/manager.conf, integration_tests/suite/helpers/bus.py, integration_tests/suite/test_calls_bus_consume.py, wazo_calld/plugins/calls/bus_consume.py, wazo_calld/plugins/calls/services.py
When a call is created the sip_call_id is assigned to the WAZO_SIP_CALL_ID
channel variable. Then when the hangup AMI event is received containing this
variable the call_ended event can be populated from this variable.
the channel helper sip_call_id function cannot be used at this point since the
channel has already disappeared
=> call_ended: add the sip_call_id field

wazo_calld/plugins/dial_mobile/service.py, wazo_calld/plugins/dial_mobile/stasis.py
when a channel hangs up, check if its a mobile trying to be reached. If its the
case, end the call for the caller
=> push_mobile: stop the wait for registration loop on call rejected

wazo_calld/plugins/dial_mobile/service.py, wazo_calld/plugins/dial_mobile/tests/test_service.py
setting the originator fixes many problems including the linkedid of the
originated call being the same as the originator channel.
this fixes almost all of the problems we had with the call-log which had no
easy way of being linked together in the previous version.
=> dial_mobile: set the originator on the originate

wazo_calld/helpers/ari_.py, wazo_calld/plugins/applications/models.py
on slow computers it is possible that the channel gets added to the bridge
before getting into stasis. This results in a 422 error from ARI and undefined
and a 500 error from calld.
I also removed the bypassStasis arguments since they were used to work around
this issue.
=> snoop: wait until the snoop channel gets into status on snoop create

wazo_calld/plugins/switchboards/confd_client_cache.py, wazo_calld/plugins/switchboards/tests/test_confd_client_cache.py
Why:
* The switchboards cache is a partial cache: it does not contain entries
that haven't already been used. The cache receives events related
to all resources, including the resources it does not know about. In
this case, we can just ignore the event.
=> switchboards: confd_cache: dont raise when invalidating unknown entry

wazo_calld/plugins/calls/bus_consume.py, wazo_calld/plugins/calls/event.py, wazo_calld/plugins/calls/notifier.py, wazo_calld/plugins/calls/plugin.py, wazo_calld/plugins/calls/services.py
The event on mute/unmute wasn't readable by user and his ACL
Since mute/unmute don't trigger ami event, we cannot send event by the
CallsBusEventHandler
Another solution should be to fix asterisk to send event when channel is
muted since this solution can be false for a fraction of second
=> call: send same event when call is updated

integration_tests/suite/helpers/base.py
on zuul or dev, hosts are too fast to see this problem and the client
have time to be created. But on slow host (Jenkins), wazo-calld can be
killed before executing this code and a WrongClient will be instantiate
=> tests: fix the try except with wrong client

integration_tests/suite/helpers/bus.py, integration_tests/suite/test_calls_bus_consume.py, wazo_calld/plugins/calls/bus_consume.py, wazo_calld/plugins/calls/event.py, wazo_calld/plugins/calls/notifier.py
Why:
* the call_updated event does not allow to detect exactly when a call
has been answered because it may be sent multiple times after the call
is answered.
=> calls: add call_answered event

integration_tests/suite/test_transfers.py, wazo_calld/plugins/transfers/state_persistor.py
transfers: add lock around transfer state persistence
transfers: ignore broken transfers index when listing
=> Pull request for WAZO-1754-broken-transfer-index

wazo_calld/plugins/dial_mobile/services.py, wazo_calld/plugins/dial_mobile/tests/test_services.py
When calling a user with multiple contacts when the first one gets answered or
when the called hangs up all devices that did not answer the call must be hung
up.
If a device is not hung up, it will keep ringing.
Instead of hanging up all channels with a state "Ringing" this change hangs up
all channels that are not in state "Up".
One of the case I have observed is that the channel will have a state "Down"
before it starts ringing. In that case, that device will keep ringing after the
phone got answered elsewhere or got hung up by the caller.
=> WAZO-1755 dial mobile: hang up all unanswered channels on answer

integration_tests/assets/docker-compose.real_asterisk.override.yml, integration_tests/assets/docker-compose.real_asterisk_conference.override.yml, integration_tests/assets/docker-compose.real_asterisk_fax.override.yml
reason: we also have removed the -f option from amid, which is highlight
this issue
=> WAZO-1762 remove foreground option from amid

integration_tests/suite/helpers/base.py, integration_tests/suite/test_relocates.py, integration_tests/suite/test_transfers.py
reason: loggers already silenced by xivo-test-helpers
=> test: remove silence loggers

etc/nginx/locations/https-available/wazo-calld
reason: The old configuration didn't keep the query string when
forwarded to wazo-calld. Since this sub location wasn't really useful,
we can remove it
=> nginx: remove specific location for max_body_size

integration_tests/suite/test_transfers.py
Why:
* Sometimes, the transfer is not yet updated.
=> tests transfers: ensure answered transfer precondtion

wazo_calld/plugins/dial_mobile/services.py
the inhibitConnectedLineUpdates parameter avoids sending an update to the
connected line to all member of the bridge when the channel are added.
This avoids the caller from seeing itself as its contact
Depends-On: https://github.com/wazo-platform/asterisk/pull/51
=> dial_mobile: fix the connected line ID of the caller

integration_tests/suite/test_conferences.py
Why:
* Better isolation of tests: preceding tests were sending bus events for
the same users when channels were hungup after the end of the test.
=> Pull request for fix-flaky-conference-test

etc/wazo-calld/config.yml, integration_tests/assets/etc/wazo-calld/conf.d/50-base.yml
Why:
* In some installs, 2 seconds can be too short for a token creation.
* There is no reason to have a shorter timeout than the default 10
seconds.
=> config: remove timeout for wazo-auth

wazo_calld/plugins/endpoints/services.py, wazo_calld/plugins/endpoints/tests/test_services.py
username is not a top level field of an endpoint SIP anymore.
=> line/trunk status: get the username from the auth_section_options

integration_tests/suite/test_adhoc_conferences.py, wazo_calld/plugins/adhoc_conferences/stasis.py
Why:
* in some cases, with send_pai = yes, the participant will see her own
caller id
=> Pull request for WAZO-1955-adhoc-conference-connectedline-update

wazo_calld/plugins/dial_mobile/services.py, wazo_calld/plugins/dial_mobile/stasis.py, wazo_calld/plugins/dial_mobile/tests/test_stasis.py
Why:
* When in a 1 on 1 conversation, if one party hangs up, the other party
should be hungup too.
* Automatic hangup has been restricted to the callcontrol Stasis
application in 2ed02320913c721eab126ab8f7272b523469da73
=> dial_mobile: automatically hang up channel left alone

integration_tests/suite/test_adhoc_conferences.py, wazo_calld/plugins/adhoc_conferences/exceptions.py, wazo_calld/plugins/adhoc_conferences/services.py
Why:
* When adding a participant of an adhoc conference with only the host,
the host would be hungup
=> adhoc conferences: forbid adding same participant

integration_tests/Makefile, integration_tests/suite/helpers/base.py, integration_tests/suite/test_adhoc_conferences.py, integration_tests/suite/test_calls.py, integration_tests/suite/test_conferences.py, integration_tests/suite/test_fax.py, integration_tests/suite/test_relocates.py, integration_tests/suite/test_voicemail.py, wazo_calld/plugins/adhoc_conferences/api.yml, wazo_calld/plugins/adhoc_conferences/services.py, wazo_calld/plugins/adhoc_conferences/stasis.py
Why:
* Homogenize naming
Why:
* More symmetric with API definition
Why:
* Preconditions should be usable in any order
* If a test modifies self.calld_client, it should not fail the
precondition
=> Pull request for WAZO-1929-adhoc-conference-refactor

integration_tests/suite/test_adhoc_conferences.py, wazo_calld/plugin_helpers/ari_.py, wazo_calld/plugins/adhoc_conferences/stasis.py
Why:
* The test test_user_remove_participant_no_call was failing due to 404
status code, as the adhoc conference variables were not yet initialized
* The two participants were already talking together, but the adhoc
conference variables not yet initialized
How:
* Assert adhoc conference events
* Send join conference events as late as possible
=> adhoc conference: fix race condition during test

integration_tests/suite/test_endpoints_bus_consume.py, wazo_calld/plugins/endpoints/bus.py, wazo_calld/plugins/endpoints/services.py, wazo_calld/plugins/endpoints/tests/test_bus.py, wazo_calld/plugins/endpoints/tests/test_services.py
The Username field of the Registry event matches the registry section client_uri
field for PJSIP endpoints.
=> trunk registrations: match Registry events to SIP trunks

integration_tests/suite/helpers/bus.py, wazo_calld/plugin_helpers/ari_.py, wazo_calld/plugin_helpers/tests/test_ari_helpers.py, wazo_calld/plugins/calls/bus_consume.py
Why:
* Purpose: make make_call_from_channel faster
=> Pull request for WAZO-2245-optimize-calld

wazo_calld/plugin_helpers/confd.py, wazo_calld/plugin_helpers/exceptions.py, wazo_calld/plugins/conferences/bus_consume.py
Why:
* Pagings create confbridge conferences that are not found in
wazo-confd.
* We want to avoid tracebacks when that happens.
=> conference: ignore joins for unknown conferences

integration_tests/suite/helpers/auth.py
Depends-on: https://github.com/wazo-platform/xivo-test-helpers/pull/50
=> test: do not use deprecated acls

wazo_calld/plugins/endpoints/bus.py, wazo_calld/plugins/endpoints/tests/test_bus.py
Local channels are not tracked by the endpoint tracking stuff which is used for
trunks and devices.
Allowing local channels to "flow" into the system generates logs which are not
useful
=> endpoints: Ignore local channels on endpoint tracking

wazo_calld/plugins/mobile/bus_consume.py
Why:
* Be able to trace the push notification events through the daemons
=> mobile push notification: add log

integration_tests/assets/docker-compose.failing_ari.override.yml, integration_tests/assets/docker-compose.yml, integration_tests/suite/test_calls.py, requirements.txt, wazo_calld/exceptions.py, wazo_calld/http.py
Depends-On: https://github.com/wazo-platform/ari-py/pull/1
Why:
* Can help find the underlying problem of an Asterisk error
=> exceptions: include original error message from ARI

integration_tests/test-requirements.txt
Why:
* Incompatibility should be fixed now
=> integration tests: restore hamcrest latest version

wazo_calld/plugins/calls/plugin.py
Why:
* Initializing DND for all users need to get all the users from
wazo-confd
* This can take a long time, depending on the number of users
* The default timeout is 10 seconds, which may no be enough
=> calls: add option "initialization_confd_timeout"

integration_tests/suite/test_switchboards.py, wazo_calld/asyncio_.py, wazo_calld/controller.py, wazo_calld/plugins/switchboards/plugin.py, wazo_calld/plugins/switchboards/services.py, wazo_calld/plugins/switchboards/tests/test_services.py
Why:
* One thread per queued call may take a significant amount of resources,
given enough calls.
* asyncio is the standard way to go
=> Pull request for WAZO-2422-switchboard-timeout-asyncio

wazo_calld/plugin_helpers/ami.py, wazo_calld/plugin_helpers/exceptions.py
This error has been crippling me for a while now and I cannot seem to figure out how to reproduce it.
```
2021-11-23 07:53:48,554 [80910] (ERROR) (xivo.pubsub): (<wazo_amid_client.client.AmidClient object at 0x
7efcf677c0f0>, AmidProtocolError('No such channel'))
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/wazo_calld/plugin_helpers/ami.py", line 22, in set_variable_ami
amid.action('Setvar', parameters)
File "/usr/lib/python3/dist-packages/wazo_amid_client/commands/action.py", line 22, in __call__
self.raise_from_protocol(r)
File "/usr/lib/python3/dist-packages/wazo_amid_client/command.py", line 27, in raise_from_protocol
raise AmidProtocolError(response)
wazo_amid_client.exceptions.AmidProtocolError: No such channel
During handling of the above exception, …
```
=> ami: set_variable_ami add parameters to the exception

wazo_calld/plugins/meetings/services.py
"No conference by that name found." is returned by Asterisk when the conference
does not exist
"No active conferences." is returned by Asterisk when NO conference are
currently happening
=> meeting: handle more errors when kicking all participants

integration_tests/suite/test_voicemail.py, requirements.txt, wazo_calld/plugin_helpers/mallow.py, wazo_calld/plugins/applications/schemas.py, wazo_calld/plugins/calls/schemas.py, wazo_calld/plugins/faxes/schemas.py, wazo_calld/plugins/relocates/schemas.py, wazo_calld/plugins/transfers/schemas.py
Depends-On: https://github.com/wazo-platform/xivo-lib-python/pull/93
=> Wazo-2638: Migration of wazo-calld from Marshmallow 3.0.0b14 to stable version 3.10.0

CHANGELOG.md, integration_tests/assets/ari_data/mock_ari.py, integration_tests/suite/helpers/hamcrest_.py, integration_tests/suite/helpers/stasis.py, integration_tests/suite/test_calls_bus_consume.py, integration_tests/suite/test_calls_stasis.py, wazo_calld/plugins/calls/api.yml, wazo_calld/plugins/calls/bus_consume.py, wazo_calld/plugins/calls/call.py, wazo_calld/plugins/calls/events.yml, wazo_calld/plugins/calls/schemas.py, wazo_calld/plugins/calls/services.py
We would like to have two fields in wazo-calld about each call:
* One called answer_time which will tells us when the call was picked up by the other end,
* The second one called hangup_time which will tell us when the call was ended.
* Write all the necessary test functions (possible scenarios), if needed.
Depends-On: https://github.com/wazo-platform/wazo-asterisk-config/pull/44
=> Add two fields in calld; one for the pick up time of a call, and another for the hang up time

integration_tests/suite/test_conferences.py
Why:
* Before, the test would fail if the event is not found at the first
attempt, instead of trying for 10 seconds
=> conference tests: fix assertion

integration_tests/assets/etc/asterisk/extensions.conf, integration_tests/suite/helpers/auth.py, integration_tests/suite/test_push_mobile.py, integration_tests/test-requirements.txt, wazo_calld/bus.py, wazo_calld/plugins/dial_mobile/bus_consume.py, wazo_calld/plugins/dial_mobile/plugin.py, wazo_calld/plugins/dial_mobile/services.py, wazo_calld/plugins/dial_mobile/tests/test_services.py
this hint is defined by wazo-confgend. it is meant to be used to monitor the
state of the usersharedline extensions. The custom hint is set to NOT_INUSE when
a mobile sessions exists for a given user. This change means that a
usersharedline will be seen as available in a group or a queue if the user has a
mobile session. Allowing the user to receive calls from the group.
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/169
Depends-On: https://github.com/wazo-platform/wazo-test-helpers/pull/71
Depends-On: https://github.com/wazo-platform/wazo-auth-keys/pull/59
=> WP-465-group-mobile-not-ringing

integration_tests/suite/test_applications.py, integration_tests/suite/test_calls.py, integration_tests/suite/test_conferences.py, integration_tests/suite/test_meetings.py, integration_tests/suite/test_relocates.py, integration_tests/suite/test_switchboards.py, integration_tests/suite/test_transfers.py, integration_tests/suite/test_voicemail.py, test-requirements.txt, wazo_calld/plugins/conferences/tests/test_notifier.py, wazo_calld/plugins/dial_mobile/tests/test_services.py, wazo_calld/plugins/voicemails/tests/test_storage.py
Why:
* pytest raised a warning about the assertion not being complete
=> Pull request for fix-test-warnings

integration_tests/suite/test_push_mobile.py
Why:
* if localhost resolves to IPv6, the wrong port will be used in
integration tests
=> integration tests: use 127.0.0.1 for docker address

integration_tests/Makefile
Why:
* We now have logs of containers in the CI, so there is no need to keep
the container to inspect logs.
* We want to know how many tests are failing
=> tests: don't stop upon failure

Dockerfile, integration_tests/assets/etc/wazo-calld/conf.d/50-base.yml
why: debug can be set in config file if needed
=> container: do not force debug mode

integration_tests/suite/helpers/amid.py, integration_tests/suite/helpers/ari_.py, integration_tests/suite/helpers/auth.py, integration_tests/suite/helpers/confd.py, integration_tests/suite/helpers/phoned.py
This change will not change anything. The goal is to make HTTP errors raise exception during tests instead of failing silently.
When trying to figure out what happened I need to look at the logs trying to find the matching timestamp to view the query result from the remote service to know the result.
=> mock: check responses and raise on error

integration_tests/suite/test_collectd.py
why: We need to wait until the StasisStart event is process before
shutdown calld. The process will write channel state on the channel to
be able to retrieve this state after a restart
=> test: add sleep before restarting calld

integration_tests/suite/test_calls_stasis.py
Why:
* Now that stasis uses the bus, we need to wait for the bus
=> test_calls_stasis: wait for bus before starting the test

wazo_calld/plugins/calls/bus_consume.py, wazo_calld/plugins/calls/tests/test_bus_consume.py
set_answered_time already logs in debug that the channel was not found. we can ignore this event if the channel is already gone
=> handle error: remove traceback

integration_tests/assets/docker-compose.yml
Why:
* Avoid creation of __pycache__ as root user
* This makes CI fail when removing test files
=> integration tests: mount docker volumes read-only

integration_tests/suite/test_calls.py
the behavior of a getChannelVar when the variable does not exists is a 404 not an empty var
This change detects the bug fixed by https://github.com/wazo-platform/wazo-calld/pull/273
=> remove an empty channel var from test setup

integration_tests/suite/helpers/real_asterisk.py, integration_tests/suite/helpers/wait_strategy.py
The calld /status is ready before Asterisk is fully booted. This waits for all modules to be loaded before starting the test
=> tests: wait for Asterisk to be fully booted

wazo_calld/plugins/transfers/stasis.py
Why:
* In some cases, the left channel may not be hungup yet (because of
Asterisk hangup processing), but we still want to hang up the other
party.
=> stasis: fix hangup channel alone

wazo_calld/plugin_helpers/ari_.py, wazo_calld/plugin_helpers/exceptions.py, wazo_calld/plugins/transfers/lock.py, wazo_calld/plugins/transfers/services.py, wazo_calld/plugins/transfers/state.py
Why:
* If event processing is slower, the two stasis channels may not get
moved to the new bridge before they are hungup by the bridge cleaner.
=> transfers: fix transfer failure when processing is slower

integration_tests/assets/ari_data/mock_ari.py, integration_tests/suite/helpers/wait_strategy.py, integration_tests/suite/test_collectd.py, wazo_calld/plugins/endpoints/plugin.py, wazo_calld/plugins/status/api.yml, wazo_calld/plugins/voicemails/plugin.py
why: according convention, every component should have a 'status' field
also add missing openapi spec definition about voicemail component
why: callback can be long to be executed and can cause some race
condition with tests
why: because real asterisk never trigger 404 when variable doesn't exist
and this will avoid a lot of unnecessary traceback during test with
XIVO_TRANSFERS_INDEX variable
=> Pull request for endpoints-plugin-status

integration_tests/suite/test_adhoc_conferences.py, wazo_calld/plugin_helpers/ari_.py, wazo_calld/plugins/adhoc_conferences/services.py
why: remove 200 lines from files, easier to read
why: using ari allow us to have more control over bridge/channel.
By using ari, we could delete bridge without issue and avoid a race
condition that occur when cleanup from callcontrol remove bridge with
only one channel
Moreover, using ari is the future to go and using dual logic (ari when
stasis and ami when non stasis channel) make logic cleaner and standard
with other usage of redirect in the code (relocate, transfers)
Note: integration already test stasis AND non stasis channels
=> WAZO-3369 move-channels-with-ari-adhoc-conference

integration_tests/assets/etc/asterisk/extensions.conf, integration_tests/suite/helpers/real_asterisk.py, integration_tests/suite/test_calls.py, wazo_calld/plugins/calls/bus_consume.py
Why:
* Pickup interceptor channel inherits variables from intercepted
channel.
=> pickup: restore channel ownership after pickup

wazo_calld/plugins/calls/bus_consume.py, wazo_calld/plugins/calls/call.py, wazo_calld/plugins/calls/services.py, wazo_calld/plugins/calls/stasis.py
the autoprov PJSIP endpoint does not contain a tenant UUID. adding it at template creation would not fix the problem for all installed systems. Adding to confgend would be possible but it would add dependencies in wazo-confgend.
WAZO-3384
=> call: remove tracebacks when dialing a provisioning code

CHANGELOG.md, integration_tests/suite/helpers/calld.py, integration_tests/suite/test_calls.py, integration_tests/suite/test_calls_stasis.py, wazo_calld/plugins/calls/api.yml, wazo_calld/plugins/calls/http.py, wazo_calld/plugins/calls/schemas.py, wazo_calld/plugins/calls/services.py, wazo_calld/plugins/calls/tests/test_http.py
https://wazo-dev.atlassian.net/browse/WAZO-3259
Depends-On: https://github.com/wazo-platform/wazo-calld-client/pull/55
=> Wazo 3259 connect user timeout

wazo_calld/plugin_helpers/ari_.py, wazo_calld/plugins/calls/tests/test_state_persistor.py
Why:
* Global vars accumulating will slow down the execution of dialplan in
Asterisk
* Asterisk 21.1.0 introduces the GLOBAL_DELETE function to delete global
vars
=> ari global vars: delete variable instead of unsetting

integration_tests/suite/test_transfers.py, wazo_calld/plugins/transfers/plugin.py, wazo_calld/plugins/transfers/services.py, wazo_calld/plugins/transfers/state.py
Why:
* Scenario:
* transfer is initiated
* channels are moved to stasis by the API thread
* channels both enter stasis into the bus thread
* the transfer object is not created yet in the API thread, preventing
the transfer to start
* the transfer is created too late by the API thread
Why:
* clarify the state we're in
Why:
* remove duplication
Why:
* avoid duplication between TransferStateReady and
TransferStateNonStasis
=> Pull request for WAZO-3690-transfer-race-condition

integration_tests/suite/test_transfers.py, wazo_calld/plugins/transfers/plugin.py, wazo_calld/plugins/transfers/services.py, wazo_calld/plugins/transfers/state.py
This reverts commits e018bc371b42e1d9b5ba43fefbafd1dc8beef7db to
80949619db2ea42f0de903cb7f27496c63717a3d.
Why:
* causes failures in wazo-acceptance tests
=> Revert WAZO-3690-transfer-race-condition

integration_tests/suite/helpers/real_asterisk.py, integration_tests/suite/test_calls.py
Why:
* Sometimes, the callee channel ID is the same as the caller channel ID
due to a race condition
=> tests pickup: remove flakiness

integration_tests/test-requirements.txt, wazo_calld/plugins/applications/services.py, wazo_calld/plugins/switchboards/services.py
Why:
* Error flow:
* The HTTP request comes in to answer the queued call
* The call to the operator is originated
* The operator answers automatically
* The operator call enters stasis and the two calls are bridged
* wazo-call tries to remove the call from the queued bridge, but
fails, since the caller channel has already been moved to another
bridge
Depends-On: https://github.com/wazo-platform/ari-py/pull/5
PRE-MERGE STEPS:
* merge ari-py PR
* tag ari-py
* update requirements.txt
=> switchboards: fix race condition raising HTTP error

wazo_calld/plugins/transfers/state.py
Why:
* The transition from non-stasis to stasis expects to find the
XIVO_TRANSFERS_$id global variable
* This variable is created *after* having sent the ARI commands to move
channels to Stasis
* Hence, there is a race condition between Asterisk setting the global
variable and wazo-calld processing the StasisStart event
=> transfers: fix race condition when starting a transfer

CHANGELOG.md, integration_tests/suite/test_applications.py, wazo_calld/plugins/applications/api.yml, wazo_calld/plugins/applications/models.py, wazo_calld/plugins/applications/schemas.py
Depends-On: https://github.com/wazo-platform/wazo-bus/pull/107
This PR adds the `conversation_id` to application_call objects (endpoints + events)
=> WP-1311: add `conversation_id` to application call

CHANGELOG.md, integration_tests/suite/test_parkings.py, wazo_calld/plugins/parking_lots/api.yml, wazo_calld/plugins/parking_lots/bus_consume.py, wazo_calld/plugins/parking_lots/dataclasses_.py, wazo_calld/plugins/parking_lots/http.py, wazo_calld/plugins/parking_lots/notifier.py, wazo_calld/plugins/parking_lots/plugin.py, wazo_calld/plugins/parking_lots/schemas.py, wazo_calld/plugins/parking_lots/services.py
Depends-On: https://github.com/wazo-platform/wazo-auth-keys/pull/78
Depends-On: https://github.com/wazo-platform/wazo-bus/pull/108
Depends-On: https://github.com/wazo-platform/wazo-calld-client/pull/58
This PR attempts to fix the parking API by making it a bit more usable
1. adds new `/parkinglots` endpoint to list all parkings and their parked calls
2. adds more information on parkinglot resource (`id` and `name`) since users can't access parking on confd
3. adds `conversation_id` on parked call object
4. adds retriever and parker information on parked call objects (caller_id name and num for each)
5.  enable unpark events
=> WAZO-3740: Fix parking API

integration_tests/assets/docker-compose.basic_rest.override.yml, integration_tests/assets/docker-compose.documentation.override.yml, integration_tests/assets/docker-compose.failing_ari.override.yml, integration_tests/assets/docker-compose.no_ari.override.yml, integration_tests/assets/docker-compose.no_auth_server.override.yml, integration_tests/assets/docker-compose.no_rabbitmq.override.yml, integration_tests/assets/docker-compose.real_asterisk.override.yml, integration_tests/assets/docker-compose.real_asterisk_conference.override.yml, integration_tests/assets/docker-compose.real_asterisk_fax.override.yml, integration_tests/assets/docker-compose.real_asterisk_no_amid.override.yml, integration_tests/assets/docker-compose.yml, integration_tests/suite/test_transfers.py, wazo_calld/plugins/transfers/http.py, wazo_calld/plugins/transfers/notifier.py, wazo_calld/plugins/transfers/plugin.py, wazo_calld/plugins/transfers/services.py, wazo_calld/plugins/transfers/stasis.py, wazo_calld/plugins/transfers/state.py, wazo_calld/plugins/transfers/state_persistor.py, wazo_calld/plugins/transfers/transfer.py, wazo_calld/plugins/transfers/transfer_lock.py
Why:
* In some circumstances, the API thread is not finished with creating
the transfer, when the Stasis thread already receives events for the
channels creating the transfer, creating weird race conditions.
=> Pull request for WAZO-3690-transfer-race-condition-fix-3

integration_tests/suite/test_applications.py
why: since we add real service token for wazo-amid, the startup is
slower than before. So we must be sure everything is ready
=> application test: wait until all services are ready

.dockerignore, integration_tests/suite/helpers/calld.py, integration_tests/suite/test_calls.py, integration_tests/suite/test_calls_bus_consume.py, integration_tests/suite/test_endpoints_bus_consume.py
Why:
* Forgetting the `leap` argument was too easy
=> Pull request for fix-integration-tests-call-direction

wazo_calld/plugins/endpoints/bus.py, wazo_calld/plugins/endpoints/services.py, wazo_calld/plugins/endpoints/tests/test_bus.py
This PR adds the trunk's endpoint to the endpoint cache when a new trunk is created so that it's status can be updated on asterisk's Registry event
Change in behavior:
- `GET /trunks` will return accurate information instead of stale data
note 1: Only sip and iax endpoints are considered, custom is not used
1. create a trunk on a tenant
2. check that /trunks returns correct registration status after Registry event (can take up to 10 seconds)
3. verify that key registered changes from `null` to either `true` or `false` (will only happen if trunk actually tries to authenticate)
=> WP-1527: update trunk status on endpoint association

integration_tests/suite/helpers/bus.py, integration_tests/suite/test_endpoints_bus_consume.py, wazo_calld/plugins/endpoints/bus.py, wazo_calld/plugins/endpoints/services.py
Why:
* line status was left to null until wazo-calld restart
=> lines API: fix line status after creation

wazo_calld/plugins/transfers/stasis.py
Why:
* Setting global var to empty creates the variable if it doesn't exist
* Accumulating global variables will significantly slow down Asterisk
over time
=> transfers: fix global var leak

integration_tests/assets/docker-compose.real_asterisk.override.yml
Why:
* Asterisk debug logs account for 80% of logs
* Asterisk debug logs are mainly useful during development, not
test failure investigation
=> integration tests: reduce logs

wazo_calld/plugins/dial_mobile/services.py, wazo_calld/plugins/dial_mobile/tests/test_services.py
Why: otherwise the destination mobile phone may continue ringing
=> [MA-1482] dial_mobile: cancel push call when hanging up

CHANGELOG.md, integration_tests/suite/test_voicemail.py, wazo_calld/plugins/voicemails/services.py
Why: it's an undocumented side-effect of a GET, which is not really RESTful since it acts directly on the accessed resource.
=> [WAZO-1908] voicemail: do not move messages to Old directory when recording accessed

requirements.txt, wazo_calld/plugins/applications/schemas.py, wazo_calld/plugins/calls/schemas.py, wazo_calld/plugins/endpoints/schemas.py, wazo_calld/plugins/faxes/schemas.py, wazo_calld/plugins/parking_lots/schemas.py, wazo_calld/plugins/relocates/schemas.py, wazo_calld/plugins/switchboards/schemas.py, wazo_calld/plugins/transfers/schemas.py
This change uses the Bookworm version of marshmallow to reduce the scope of changes that are going to happen when doing the upgrade
=> Use marshmallow version 3.18.0 from Bookworm
