wazo-platform/wazo-calld

- debian/wazo-calld.postinst
debian: remove not migrated log file
debian: do the logfile migration before create new one
> Pull request for WAZO-844-fix-logfile

- integration_tests/suite/helpers/confd.py
- integration_tests/suite/test_conferences.py
- wazo_calld/helpers/confd.py
- wazo_calld/helpers/exceptions.py
- wazo_calld/plugins/conferences/api.yml
- wazo_calld/plugins/conferences/bus_consume.py
- wazo_calld/plugins/conferences/events.yml
- wazo_calld/plugins/conferences/exceptions.py
- wazo_calld/plugins/conferences/notifier.py
- wazo_calld/plugins/conferences/plugin.py
- wazo_calld/plugins/conferences/resources.py
- wazo_calld/plugins/conferences/schemas.py
- wazo_calld/plugins/conferences/services.py
- wazo_calld/plugins/conferences/tests/test_notifier.py
conferences: send events to other participants on participant join/leave
conferences: add /users/me/conferences/id/participants
> Users can list conference participants

- integration_tests/suite/helpers/bus.py
- integration_tests/suite/helpers/confd.py
- integration_tests/suite/test_applications.py
- wazo_calld/ari_.py
- wazo_calld/bus.py
- wazo_calld/plugins/applications/caches.py
- wazo_calld/plugins/applications/plugin.py
- wazo_calld/plugins/applications/services.py
- wazo_calld/plugins/applications/stasis.py
application: trigger actions on application events
application: add application cache tests
application: add moh cache tests
application: rename variable destination_created
application: listen on moh events to update cache
application: listen on application events to update cache
> Pull request for WAZO-907-cache-application

- integration_tests/suite/test_push_mobile.py
- wazo_calld/bus.py
- wazo_calld/plugins/mobile/bus_consume.py
mobile: add test
bus: fix typo in variable name
> Pull request for WAZO-922-push-mobile-improvment

- Dockerfile
- debian/wazo-calld.postinst
- debian/wazo-calld.service
- etc/wazo-calld/config.yml
- wazo_calld/config.py
since buster /var/run is a now a symlink to /run
> use /run instead of /var/run

- CHANGELOG.md
- integration_tests/suite/helpers/base.py
- integration_tests/suite/test_calls.py
- integration_tests/suite/test_conferences.py
- integration_tests/suite/test_relocates.py
- wazo_calld/plugin_helpers/ami.py
- wazo_calld/plugin_helpers/ari_.py
- wazo_calld/plugins/applications/services.py
- wazo_calld/plugins/applications/stasis.py
- wazo_calld/plugins/calls/api.yml
- wazo_calld/plugins/calls/call.py
- wazo_calld/plugins/calls/event.py
- wazo_calld/plugins/calls/events.yml
- wazo_calld/plugins/calls/http.py
- wazo_calld/plugins/calls/notifier.py
- wazo_calld/plugins/calls/plugin.py
- wazo_calld/plugins/calls/schemas.py
- wazo_calld/plugins/calls/services.py
- wazo_calld/plugins/calls/tests/test_services.py
Depends-on: https://github.com/wazo-platform/wazo-calld-client/pull/20
> Wazo 1501 mute unmute api for calls

- .gitignore
- integration_tests/Makefile
- integration_tests/suite/helpers/base.py
- integration_tests/suite/helpers/calld.py
- integration_tests/suite/test_ari.py
- integration_tests/suite/test_authentication.py
- integration_tests/suite/test_calls.py
- integration_tests/suite/test_transfers.py
- integration_tests/test-requirements.txt
- setup.cfg
- test-requirements.txt
- tox.ini
use real calld client for list_calls
use real calld client for test_authentication
use pytest instead of nosetests
Depends-on: https://github.com/wazo-platform/wazo-calld-client/pull/21
> Pull request for improve-calld-tests

- integration_tests/suite/test_relocates.py
Why:
* The test test_given_relocate_completion_api_when_api_complete_then_relocate_completed
sometimes fails with the error "Requested completion is too early".
> relocates: wait for relocate event before starting test

- integration_tests/suite/test_conferences.py
- wazo_calld/plugins/conferences/bus_consume.py
- wazo_calld/plugins/conferences/events.yml
- wazo_calld/plugins/conferences/notifier.py
conferences: add talking/stop event for users
conferences: add missing headers on participant left event
> Pull request for WAZO-1698-conference-user-events

- integration_tests/suite/test_applications.py
- wazo_calld/plugins/dial_mobile/services.py
- wazo_calld/plugins/transfers/services.py
- wazo_calld/plugins/transfers/state.py
fix styling issues
tranfers: fix blind transfer race condition
> Pull request for WAZO-1739-blind-transfer-status

- integration_tests/assets/etc/wazo-calld/conf.d/20-adapter-api.yml
- wazo_calld/http_server.py
http_server: use logging helpers from lib-python
http_server: remove unused flask application
> Pull request for use-lib-python-request-logging

- integration_tests/suite/test_voicemail.py
- wazo_calld/plugin_helpers/confd.py
Depends-On: https://github.com/wazo-platform/wazo-calld/pull/90
> WAZO-1370: fix 500 error when user has no voicemail

- CHANGELOG.md
- integration_tests/suite/helpers/bus.py
- integration_tests/suite/test_applications.py
- integration_tests/suite/test_calls.py
- integration_tests/suite/test_calls_bus_consume.py
- integration_tests/suite/test_switchboards.py
- wazo_calld/plugin_helpers/ami.py
- wazo_calld/plugins/api/api.yml
- wazo_calld/plugins/applications/api.yml
- wazo_calld/plugins/applications/http.py
- wazo_calld/plugins/applications/plugin.py
- wazo_calld/plugins/applications/schemas.py
- wazo_calld/plugins/applications/services.py
- wazo_calld/plugins/calls/api.yml
- wazo_calld/plugins/calls/bus_consume.py
- wazo_calld/plugins/calls/http.py
- wazo_calld/plugins/calls/plugin.py
- wazo_calld/plugins/calls/schemas.py
- wazo_calld/plugins/calls/services.py
- wazo_calld/plugins/calls/tests/test_schemas.py
- wazo_calld/plugins/calls/tests/test_services.py
Depends-On: https://github.com/wazo-platform/wazo-calld-client/pull/24
Depends-On: https://github.com/wazo-platform/wazo-auth-keys/pull/22
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/20
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1566
> WAZO-1566: add send DTMF action to calls

- CHANGELOG.md
- integration_tests/suite/test_voicemail.py
- wazo_calld/plugins/voicemails/api.yml
- wazo_calld/plugins/voicemails/http.py
- wazo_calld/plugins/voicemails/services.py
Depends-on: https://github.com/wazo-platform/wazo-calld-client/pull/26
> add HEAD voicemail/greeting

- integration_tests/suite/test_applications.py
test: fix async application event tests
test: wait until applications are really created
> Pull request for fix-flaky-application-tests

- CHANGELOG.md
- integration_tests/suite/test_voicemail.py
- wazo_calld/plugins/voicemails/api.yml
- wazo_calld/plugins/voicemails/http.py
Depends-on: https://github.com/wazo-platform/wazo-calld-client/pull/27
> Pull request for WAZO-1800-head-user-voicemail

- integration_tests/suite/test_conferences.py
- wazo_calld/plugins/calls/bus_consume.py
Why:
* If someones enters or leaves a bridge, all calls should have their
"talking_to" attribute updated.
> WAZO-1859 calls: send call_updated to bridge participants

- Dockerfile
- debian/wazo-calld.service
- etc/wazo-calld/config.yml
- wazo_calld/config.py
- wazo_calld/main.py
reason: systemd restart remove monit usage based on pid file
> remove usage of PID file and use systemd options

- CHANGELOG.md
- etc/wazo-calld/config.yml
- integration_tests/assets/docker-compose.basic_rest.override.yml
- integration_tests/assets/docker-compose.yml
- integration_tests/assets/etc/wazo-calld/conf.d/50-base.yml
- integration_tests/assets/phoned_data/mock-wazo-phoned.py
- integration_tests/suite/helpers/base.py
- integration_tests/suite/helpers/phoned.py
- integration_tests/suite/test_calls.py
- wazo_calld/config.py
- wazo_calld/phoned.py
- wazo_calld/plugins/calls/api.yml
- wazo_calld/plugins/calls/http.py
- wazo_calld/plugins/calls/plugin.py
- wazo_calld/plugins/calls/schemas.py
- wazo_calld/plugins/calls/services.py
- wazo_calld/plugins/calls/tests/test_services.py
Depends-On: https://github.com/wazo-platform/wazo-calld-client/pull/28
> WAZO-1503: hold/unhold call

- CHANGELOG.md
- integration_tests/assets/phoned_data/mock-wazo-phoned.py
- integration_tests/suite/test_calls.py
- wazo_calld/exceptions.py
- wazo_calld/phoned.py
- wazo_calld/plugins/calls/api.yml
- wazo_calld/plugins/calls/http.py
- wazo_calld/plugins/calls/plugin.py
- wazo_calld/plugins/calls/services.py
Depends-On: https://github.com/wazo-platform/wazo-calld-client/pull/33
> WAZO-1926: add call answer

- integration_tests/suite/test_adhoc_conferences.py
- wazo_calld/plugin_helpers/ari_.py
- wazo_calld/plugins/adhoc_conferences/services.py
- wazo_calld/plugins/adhoc_conferences/stasis.py
> Pull request for WAZO-1916-adhoc-conf-hangup

- CHANGELOG.md
- integration_tests/suite/test_adhoc_conferences.py
- wazo_calld/plugins/adhoc_conferences/api.yml
- wazo_calld/plugins/adhoc_conferences/http.py
- wazo_calld/plugins/adhoc_conferences/plugin.py
- wazo_calld/plugins/adhoc_conferences/services.py
- wazo_calld/plugins/adhoc_conferences/stasis.py
Depends-On: https://github.com/wazo-platform/wazo-calld-client/pull/32
Depends-On: wazo-platform/xivo-bus#25
Depends-On: https://github.com/wazo-platform/wazo-calld/pull/118
> Pull request for WAZO-1924-adhoc-conference-deletion

- integration_tests/suite/helpers/real_asterisk.py
- integration_tests/suite/test_adhoc_conferences.py
- integration_tests/suite/test_relocates.py
- integration_tests/suite/test_transfers.py
- wazo_calld/plugins/adhoc_conferences/api.yml
- wazo_calld/plugins/adhoc_conferences/exceptions.py
- wazo_calld/plugins/adhoc_conferences/services.py
- wazo_calld/plugins/adhoc_conferences/stasis.py
Depends-On: wazo-platform/wazo-calld-client#32
Depends-On: #122
> Pull request for WAZO-1925-adhoc-conference-corner-cases

- integration_tests/suite/test_adhoc_conferences.py
- wazo_calld/plugins/adhoc_conferences/stasis.py
Depends-On: wazo-platform/wazo-calld-client#32
Depends-On: wazo-platform/xivo-bus#25
Depends-On: https://github.com/wazo-platform/wazo-calld/pull/120
> Pull request for WAZO-1928-adhoc-conference-caller-id

- wazo_calld/bus.py
- wazo_calld/collectd.py
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/30
> bus: use correct policy for publishing

- integration_tests/assets/docker-compose.yml
- integration_tests/suite/helpers/confd.py
- integration_tests/suite/test_voicemail.py
- wazo_calld/plugin_helpers/confd.py
- wazo_calld/plugins/voicemails/http.py
- wazo_calld/plugins/voicemails/services.py
Depends-on: https://github.com/wazo-platform/wazo-confd-client/pull/24
Depends-on: https://github.com/wazo-platform/xivo-test-helpers/pull/40
> Pull request for WAZO-2108-use-one-request-for-voicemail

- integration_tests/assets/etc/wazo-amid/config.yml
to generate its refreshtoken to know its master tenant for REST API
Depends-on: https://github.com/wazo-platform/wazo-amid/pull/31
> test: amid config need to have auth username/password

- CHANGELOG.md
- integration_tests/suite/test_calls.py
- wazo_calld/plugin_helpers/ami.py
- wazo_calld/plugin_helpers/ari_.py
- wazo_calld/plugins/calls/api.yml
- wazo_calld/plugins/calls/call.py
- wazo_calld/plugins/calls/http.py
- wazo_calld/plugins/calls/plugin.py
- wazo_calld/plugins/calls/schemas.py
- wazo_calld/plugins/calls/services.py
Depends-On: https://github.com/wazo-platform/wazo-calld-client/pull/35
You should also check the wazo-auth-keys PR: https://github.com/wazo-platform/wazo-auth-keys/pull/33
> WAZO-2171: call record stop

- wazo_calld/plugins/calls/services.py
- wazo_calld/plugins/calls/tests/test_services.py
this avoid overwritting an existing recording
> recordings: update the recording filename at each start

- integration_tests/suite/helpers/confd.py
- wazo_calld/plugins/switchboards/confd.py
- wazo_calld/plugins/switchboards/services.py
- wazo_calld/plugins/switchboards/stasis.py
- wazo_calld/plugins/switchboards/tests/test_services.py
- wazo_calld/plugins/switchboards/tests/test_stasis.py
Depends-On: https://github.com/wazo-platform/wazo-confd/pull/200
> Wazo 2393 switchboard moh

- debian/control
- integration_tests/suite/helpers/constants.py
- integration_tests/suite/test_config.py
- requirements.txt
- setup.py
- wazo_calld/auth.py
- wazo_calld/config.py
- wazo_calld/controller.py
- wazo_calld/exceptions.py
- wazo_calld/http.py
- wazo_calld/plugins/config/api.yml
- wazo_calld/plugins/config/http.py
- wazo_calld/plugins/config/plugin.py
- wazo_calld/plugins/config/schemas.py
- wazo_calld/plugins/config/service.py
Depends-On: https://github.com/wazo-platform/wazo-calld-client/pull/38
> add /config API allowing change of debug setting

- integration_tests/assets/etc/asterisk/extensions-conference.conf
- integration_tests/suite/helpers/confd.py
- integration_tests/suite/test_meetings.py
- setup.py
- wazo_calld/config.py
- wazo_calld/plugin_helpers/confd.py
- wazo_calld/plugin_helpers/exceptions.py
- wazo_calld/plugins/conferences/tests/test_bus_consume.py
- wazo_calld/plugins/meetings/api.yml
- wazo_calld/plugins/meetings/bus_consume.py
- wazo_calld/plugins/meetings/events.yml
- wazo_calld/plugins/meetings/exceptions.py
- wazo_calld/plugins/meetings/http.py
- wazo_calld/plugins/meetings/notifier.py
- wazo_calld/plugins/meetings/plugin.py
- wazo_calld/plugins/meetings/schemas.py
- wazo_calld/plugins/meetings/services.py
- wazo_calld/plugins/meetings/tests/test_bus_consume.py
Depends-On: https://github.com/wazo-platform/wazo-confd-client/pull/29
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/42
Depends-On: https://github.com/wazo-platform/xivo-test-helpers/pull/55
Depends-On: https://github.com/wazo-platform/wazo-calld-client/pull/40
> meetings: add join/left events

- wazo_calld/plugins/calls/bus_consume.py
When a user enables/disables it's DnD feature wazo calld pauses/unpauses it's
usersharedlines interface. If the user is not a member of any group Asterisk
return the error 'Interface not found' which results in a huge traceback in the
log file.
This error should be ignored
> WAZO-2626: calls dnd event: ignore unknown interface

- integration_tests/suite/helpers/ari_.py
- integration_tests/suite/helpers/base.py
- integration_tests/suite/helpers/real_asterisk.py
- integration_tests/suite/helpers/wait_strategy.py
- integration_tests/test-requirements.txt
why: to have the latest docker-compose
> use docker-compose from binary instead of python

- CHANGELOG.md
- etc/nginx/locations/https-available/wazo-calld
- etc/nginx/locations/https-available/wazo-calld-shared.conf
- integration_tests/assets/etc/wazo-calld/conf.d/20-real-asterisk.yml
- integration_tests/suite/test_meetings.py
- wazo_calld/config.py
- wazo_calld/plugin_helpers/confd.py
- wazo_calld/plugins/meetings/api.yml
- wazo_calld/plugins/meetings/http.py
- wazo_calld/plugins/meetings/plugin.py
- wazo_calld/plugins/meetings/schemas.py
- wazo_calld/plugins/meetings/services.py
Depends-On: https://github.com/wazo-platform/wazo-calld-client/pull/45
> Wazo 2656 meeting limit api

- integration_tests/suite/test_applications.py
- integration_tests/suite/test_calls.py
- integration_tests/suite/test_calls_recording.py
- integration_tests/suite/test_fax.py
the are some fails some of the time when running in the CI
> tests: increase multiple timeouts

- integration_tests/suite/test_fax.py
- wazo_calld/plugins/faxes/api.yml
- wazo_calld/plugins/faxes/schemas.py
- wazo_calld/plugins/faxes/services.py
add support for ivr_extension and wait_time
changes made:
Depends-on: https://github.com/wazo-platform/xivo-config/pull/50
Depends-on: https://github.com/wazo-platform/wazo-calld-client/pull/44
> WAZO-2704 - Add extension for fax ivr

- integration_tests/assets/etc/asterisk/extensions-conference.conf
- integration_tests/suite/helpers/confd.py
- integration_tests/suite/test_meetings.py
- wazo_calld/plugin_helpers/ari_.py
- wazo_calld/plugin_helpers/confd.py
- wazo_calld/plugins/meetings/api.yml
- wazo_calld/plugins/meetings/bus_consume.py
- wazo_calld/plugins/meetings/exceptions.py
- wazo_calld/plugins/meetings/http.py
- wazo_calld/plugins/meetings/plugin.py
- wazo_calld/plugins/meetings/services.py
Depends-On: https://github.com/wazo-platform/wazo-calld-client/pull/46
> Pull request for WAZO-2746-kick-meeting-participant

- CHANGELOG.md
- integration_tests/suite/helpers/bus.py
- integration_tests/suite/test_calls.py
- integration_tests/suite/test_calls_bus_consume.py
- wazo_calld/plugin_helpers/ari_.py
- wazo_calld/plugins/calls/api.yml
- wazo_calld/plugins/calls/bus_consume.py
- wazo_calld/plugins/calls/call.py
- wazo_calld/plugins/calls/schemas.py
- wazo_calld/plugins/calls/services.py
- wazo_calld/plugins/calls/stasis.py
- wazo_calld/plugins/calls/tests/test_services.py
Depends-On: https://github.com/wazo-platform/xivo-config/pull/66
Depends-On: https://github.com/wazo-platform/wazo-asterisk-config/pull/47
> WAZO-2096: add call direction

- integration_tests/suite/helpers/constants.py
- wazo_calld/collectd.py
- wazo_calld/config.py
- wazo_calld/controller.py
- wazo_calld/plugins/calls/stat_sender.py
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/82
Why:
* Drop-in replacement that allows to drop deprecated dependencies in xivo-bus
> WAZO-2994: Change Collectd to use mixin

- integration_tests/suite/helpers/calld.py
- integration_tests/suite/test_calls.py
- wazo_calld/ari_.py
- wazo_calld/plugins/calls/call.py
- wazo_calld/plugins/calls/services.py
Depends-On: https://github.com/wazo-platform/wazo-calld/pull/267
> Wazo 3207 channel constants v2

- integration_tests/assets/amid_data/mock-wazo-amid.py
- integration_tests/assets/ari_data/mock_ari.py
- integration_tests/assets/ari_data/mock_ari_fail.py
- integration_tests/assets/phoned_data/mock-wazo-phoned.py
- integration_tests/docker/Dockerfile-ari-mock
Depends-on: https://github.com/wazo-platform/wazo-test-helpers/pull/84
> Update Mocks to Python 3 and Bullseye

- integration_tests/suite/conftest.py
Depends-On: https://github.com/wazo-platform/wazo-test-helpers/pull/90
> integration tests: add markers for test start and end

- wazo_calld/plugins/dial_mobile/services.py
- wazo_calld/plugins/dial_mobile/tests/test_services.py
> Pull request for WAZO-3560-mobile-intercept-after-abandon

- integration_tests/suite/test_transfers.py
- wazo_calld/plugins/transfers/plugin.py
- wazo_calld/plugins/transfers/services.py
- wazo_calld/plugins/transfers/state.py
This reverts commit 5e6d143fc71ac9f9f6bd92062a621300729028c7.
> Revert "Revert WAZO-3690-transfer-race-condition"

- wazo_calld/ari_.py
- wazo_calld/plugins/relocates/stasis.py
- wazo_calld/plugins/switchboards/stasis.py
- wazo_calld/plugins/transfers/stasis.py
> Pull request for homogenize-stasis-start-logging

- integration_tests/suite/helpers/auth.py
- wazo_calld/auth.py
Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/140
> use flask user object to retrieve user_uuid

- wazo_calld/auth.py
- wazo_calld/http.py
- wazo_calld/http_server.py
Depends-on: https://github.com/wazo-platform/xivo-lib-python/pull/141
> Pull request for WP-1540-module-auth-verifier-refactor

- debian/wazo-calld.dirs
- debian/wazo-calld.service
- etc/rsyslog.d/99-wazo-calld.conf
> WAZO-3682: disable logs to rsyslog

- wazo_calld/http_server.py
> HTTP server: apply cheroot patch

- integration_tests/suite/helpers/real_asterisk.py
- integration_tests/suite/test_transfers.py
- wazo_calld/ari_.py
- wazo_calld/plugin_helpers/ari_.py
- wazo_calld/plugins/transfers/ari_helpers.py
- wazo_calld/plugins/transfers/notifier.py
- wazo_calld/plugins/transfers/services.py
- wazo_calld/plugins/transfers/stasis.py
- wazo_calld/plugins/transfers/state.py
- wazo_calld/plugins/transfers/state_persistor.py
- wazo_calld/plugins/transfers/tests/test_transfer.py
- wazo_calld/plugins/transfers/transfer.py
lotta basic refactoring(method extractions, moving stuff around) in the lot.
> WP 1333 attended transfer moh

- integration_tests/suite/test_applications.py
- wazo_calld/plugins/applications/notifier.py
- wazo_calld/plugins/applications/stasis.py
Depends-On: https://github.com/wazo-platform/wazo-bus/pull/115
> [WP-1600] Add missing conversation_id and call_id to DTMF and PlaybackFinished events

- wazo_calld/plugins/calls/services.py
> recording: replicate group logic for queues

- wazo_calld/plugins/transfers/state.py
- Fix wrong args to logger.debug
- Remove None value from debug
> transfers: fix traceback with wrong logging

- CHANGELOG.md
- integration_tests/suite/test_applications.py
- wazo_calld/plugins/applications/api.yml
- wazo_calld/plugins/applications/schemas.py
Depends-On: https://github.com/wazo-platform/asterisk/pull/152
> [WAZO-1939] Add application playback state in schema

- wazo_calld/plugins/calls/services.py
the local channel gets optimized out later
> recording start: use concrete channel

- wazo_calld/plugins/calls/services.py
This reverts commit 0f33b8653a7967ead9083a7650d13e416cc82ff0.
> Revert "recording start: use concrete channel"

- .pre-commit-config.yaml
- Dockerfile
- README.md
- debian/control
- integration_tests/assets/docker-compose.yml
- integration_tests/docker/Dockerfile-ari-mock
- integration_tests/suite/test_parkings.py
- pyproject.toml
- requirements.txt
- tox.ini
- wazo_calld/plugin_helpers/ari_.py
- wazo_calld/plugins/applications/caches.py
- wazo_calld/plugins/calls/services.py
- wazo_calld/plugins/parking_lots/bus_consume.py
- wazo_calld/plugins/parking_lots/plugin.py
- wazo_calld/plugins/parking_lots/services.py
- zuul.yaml
- **bullseye -> bookworm**
- **pyupgrade 3.9 -> 3.11**
- **requirements: bump to bookworm**
> WAZO 4304 bookworm
